# Generated by Django 4.1.2 on 2022-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="transaction",
            field=models.CharField(choices=[("I", "IN"), ("O", "ON")], max_length=2),
        ),
    ]
