# Generated by Django 4.1.2 on 2022-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_stock_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="transaction",
            field=models.CharField(choices=[("I", "IN"), ("O", "OUT")], max_length=2),
        ),
    ]
