# Generated by Django 4.1.2 on 2022-10-07 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0003_alter_stock_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction",
                    models.SmallIntegerField(choices=[(1, "IN"), (0, "OUT")]),
                ),
                ("quantity", models.SmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "price_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="stock.firm",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock_quantity",
            new_name="stock",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.AddField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="stock.product",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
